import { PrismaClient } from '@prisma/client';
import {hashPassword} from '../lib/auth';
const prisma=new PrismaClient();
const companies=[['Lezzet Park Catering','lezzet-park-catering'],['Gurme Catering','gurme-catering'],['Premium Catering','premium-catering'],['Organik Lezzetler','organik-lezzetler'],['Elite Catering','elite-catering']];
const DEMO_PASSWORD='Demo12345!';
async function main(){
 const cities=['İstanbul','Ankara','İzmir','Bursa','Antalya'].map(n=>({name:n,slug:n.toLocaleLowerCase('tr').replaceAll('ı','i').replaceAll('ş','s').replaceAll('ğ','g').replaceAll('ü','u').replaceAll('ö','o').replaceAll('ç','c')}));
 for(const c of cities) await prisma.city.upsert({where:{slug:c.slug},update:{},create:c});
 const cats=[['Kurumsal Yemek','kurumsal-yemek'],['Düğün & Davet','dugun-davet'],['Toplantı & Seminer','toplanti-seminer'],['VIP Catering','vip-catering'],['Kokteyl','kokteyl']];
 for(const [name,slug] of cats) await prisma.category.upsert({where:{slug},update:{},create:{name,slug}});
 const plans=[['FREE','Ücretsiz',0,0,0],['STARTER','Starter',1490,14900,14],['PRO','Pro',2990,29900,14],['PREMIUM','Premium',5990,59900,30]];
 for(const [code,name,m,y,t] of plans) await prisma.subscriptionPlan.upsert({where:{code},update:{},create:{code,name,priceMonthly:m,priceYearly:y,trialDays:t,features:{video:code!=='FREE',analytics:code==='PRO'||code==='PREMIUM',promotion:code==='PREMIUM'},limits:{listings:code==='FREE'?1:code==='STARTER'?1:code==='PRO'?5:999}}});
 const city=await prisma.city.findUnique({where:{slug:'istanbul'}}); const cat=await prisma.category.findUnique({where:{slug:'dugun-davet'}});
 for(let i=0;i<companies.length;i++){const [name,slug]=companies[i]; const u=await prisma.user.upsert({where:{email:`demo${i+1}@catefind.local`},update:{passwordHash:hashPassword(DEMO_PASSWORD),emailVerifiedAt:new Date()},create:{email:`demo${i+1}@catefind.local`,name,role:'COMPANY',passwordHash:hashPassword(DEMO_PASSWORD),emailVerifiedAt:new Date()}}); const co=await prisma.company.upsert({where:{slug},update:{},create:{name,slug,status:'ACTIVE',verified:true,description:'Bu firma CateFind demo verisidir; gerçek bir işletmeyi temsil etmez.',cityId:city?.id,rating:4.6-i*.15,reviewCount:18+i*7,responseMinutes:30+i*8}}); await prisma.companyUser.upsert({where:{companyId_userId:{companyId:co.id,userId:u.id}},update:{},create:{companyId:co.id,userId:u.id}}); await prisma.companyProfile.upsert({where:{companyId:co.id},update:{},create:{companyId:co.id,completeness:82+i*3,services:['Düğün','Kurumsal'],cuisines:['Türk Mutfağı','Akdeniz'],serviceAreas:['İstanbul']}}); await prisma.companyCategory.upsert({where:{companyId_categoryId:{companyId:co.id,categoryId:cat!.id}},update:{},create:{companyId:co.id,categoryId:cat!.id}}); const listing=await prisma.listing.upsert({where:{slug:`${slug}-500-kisilik-dugun-menusu`},update:{},create:{companyId:co.id,categoryId:cat!.id,cityId:city?.id,title:`${name} · 500 Kişilik Düğün Menüsü`,subtitle:'Şık sunum, deneyimli servis ekibi ve uçtan uca organizasyon.',description:'Demo ilanıdır. Menü, servis, kurulum ve teslimat seçenekleriyle esnek paket.',status:'APPROVED',priceFrom:42500+i*5500,priceType:'Paket',minPeople:100,maxPeople:800,setup:true,staff:true,delivery:true,halal:true,publishedAt:new Date()}}); await prisma.listingMedia.createMany({data:[{listingId:listing.id,type:'image',url:'https://images.unsplash.com/photo-1555244162-803834f70033?w=1200&q=80',alt:'Catering sunumu',sortOrder:0},{listingId:listing.id,type:'image',url:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&q=80',alt:'Davet masası',sortOrder:1}],skipDuplicates:true}); }
 const customer=await prisma.user.upsert({where:{email:'musteri@catefind.local'},update:{passwordHash:hashPassword(DEMO_PASSWORD),emailVerifiedAt:new Date()},create:{email:'musteri@catefind.local',name:'Demo Müşteri',role:'CUSTOMER',passwordHash:hashPassword(DEMO_PASSWORD),emailVerifiedAt:new Date()}}); await prisma.customerProfile.upsert({where:{userId:customer.id},update:{},create:{userId:customer.id}});
 console.log(`Seed tamamlandı. Demo hesap şifresi: ${DEMO_PASSWORD}`);
}
main().finally(()=>prisma.$disconnect());
