'use client';
import Link from 'next/link';
import { ArrowRight, BadgeCheck, BarChart3, Bell, CalendarDays, Heart, LayoutDashboard, MessageCircle, MoreHorizontal, PackageCheck, Search, Settings, Star, Store, Users, UtensilsCrossed } from 'lucide-react';

export const firms = [
 {name:'Lezzet Durağı Catering',slug:'lezzet-duragi-catering',city:'İstanbul',rating:4.8,reviews:120,response:18,price:42500,tags:['Düğün & Davet','Kurumsal'],image:'https://images.unsplash.com/photo-1555244162-803834f70033?w=1200&q=85'},
 {name:'Evin Yemekleri',slug:'evin-yemekleri',city:'İstanbul',rating:4.6,reviews:98,response:24,price:38500,tags:['Ev Yemekleri','Kurumsal'],image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&q=85'},
 {name:'Şefin Sofrası',slug:'sefin-sofrasi',city:'İstanbul',rating:4.9,reviews:210,response:20,price:62000,tags:['VIP Catering','Özel Etkinlik'],image:'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=1200&q=85'},
 {name:'Anadolu Catering',slug:'anadolu-catering',city:'İstanbul',rating:4.8,reviews:190,response:16,price:36000,tags:['Toplu Yemek','Kurumsal'],image:'https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=85'},
 {name:'Marin Food',slug:'marin-food',city:'İstanbul',rating:4.8,reviews:76,response:28,price:51000,tags:['Kokteyl','Düğün & Davet'],image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&q=85'},
 {name:'Gurme Tabak',slug:'gurme-tabak',city:'İstanbul',rating:4.7,reviews:84,response:22,price:45000,tags:['Özel Etkinlik','VIP Catering'],image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=85'}
];

export function BrandMark(){return <span className="logo-mark" aria-hidden="true"><UtensilsCrossed size={18}/></span>}
export function PageHeader({title,description,eyebrow='CateFind'}:{title:string;description?:string;eyebrow?:string}){return <div className="page-title"><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>}
export function FirmCard({firm,compact=false}:{firm:typeof firms[number];compact?:boolean}){return <article className="card company-card"><div className="company-photo" style={{height:compact?150:190}}><img src={firm.image} alt={firm.name}/><span className="chip" style={{position:'absolute',left:12,top:12,background:'#fff'}}>Doğrulanmış</span><button className="heart" aria-label="Favorilere ekle"><Heart size={17}/></button></div><div className="company-body"><Link href={`/firma/${firm.slug}`} className="company-title"><h3>{firm.name} <BadgeCheck size={16} style={{display:'inline',color:'var(--green)'}}/></h3><span className="rating">★ {firm.rating}</span></Link><div className="muted">{firm.city} · {firm.reviews} yorum</div><div className="chips">{firm.tags.map(tag=><span className="chip" key={tag}>{tag}</span>)}</div><div className="meta"><span>◷ Ortalama {firm.response} dk cevap</span></div><div className="company-foot"><span>₺{firm.price.toLocaleString('tr-TR')}+</span><Link href={`/firma/${firm.slug}`} style={{color:'var(--green)'}}>İncele <ArrowRight size={14} style={{display:'inline'}}/></Link></div></div></article>}
export function MarketplaceFilters(){return <aside className="card filters"><div style={{display:'flex',justifyContent:'space-between'}}><b>Filtreler</b><button style={{border:0,background:'none',color:'var(--green)',fontSize:12,fontWeight:800}}>Temizle</button></div><div className="filter"><h4>Şehir</h4><select className="field" style={{width:'100%'}}><option>İstanbul</option><option>Ankara</option><option>İzmir</option></select></div><div className="filter"><h4>Hizmet kategorisi</h4>{['Kurumsal Yemek','Düğün & Davet','Okul Yemekleri','Özel Etkinlikler'].map(x=><label className="check" key={x}><input type="checkbox"/> {x}</label>)}</div><div className="filter"><h4>Puan</h4>{['5 yıldız','4 yıldız ve üzeri','3 yıldız ve üzeri'].map(x=><label className="check" key={x}><input type="radio" name="rating"/> {x}</label>)}</div><div className="filter"><h4>Özellik</h4>{['Helal Sertifikası','Vegan','Hızlı Teslimat'].map(x=><label className="check" key={x}><input type="checkbox"/> {x}</label>)}</div><button className="btn btn-green" style={{width:'100%',marginTop:16}}>Sonuçları göster</button></aside>}
const links={Müşteri:['Ana Sayfa','Taleplerim','Tekliflerim','Mesajlarım','Favorilerim','Profil','Ayarlar'],Firma:['Ana Sayfa','Talepler','Teklifler','İlanlar','Menüler','Mesajlar','Yorumlar','Analitik','Profil','Ayarlar'],Admin:['Dashboard','Firmalar','Kullanıcılar','Talepler','Teklifler','İlanlar','Yorumlar','Kategoriler','Raporlar','Ayarlar']} as const;
const hrefFor=(role:string,item:string)=>{if(role==='Firma'){const m:{[key:string]:string}={'Ana Sayfa':'/firma/panel','Talepler':'/firma/talepler','Teklifler':'/firma/teklifler','İlanlar':'/firma/ilanlar','Mesajlar':'/firma/mesajlar','Profil':'/firma/panel','Ayarlar':'/firma/panel'};return m[item]||'/firma/panel'}if(role==='Admin')return item==='Dashboard'?'/admin':'/admin';const m:{[key:string]:string}={'Ana Sayfa':'/musteri/panel','Taleplerim':'/musteri/talepler','Tekliflerim':'/musteri/teklifler','Mesajlarım':'/musteri/mesajlar','Favorilerim':'/favorilerim','Profil':'/musteri/panel','Ayarlar':'/musteri/panel'};return m[item]||'/musteri/panel'};
export function DashboardSidebar({role='Müşteri',active='Ana Sayfa'}:{role?:string;active?:string}){const items=links[role as keyof typeof links]||links.Müşteri;return <aside className="sidebar"><Link href="/" className="side-logo"><BrandMark/>CateFind</Link><div className="eyebrow" style={{color:'#49c98a',margin:'0 10px 10px'}}>{role} Paneli</div><nav>{items.map((item,i)=><Link key={item} href={hrefFor(role,item)} className={`side-link ${item===active?'active':''}`}>{i===0?<LayoutDashboard size={17}/>:i===1?<CalendarDays size={17}/>:i===2?<PackageCheck size={17}/>:i===3?<Store size={17}/>:i===5?<MessageCircle size={17}/>:i===6?<Star size={17}/>:i===7?<BarChart3 size={17}/>:i===8?<Users size={17}:<Settings size={17}/>} {item}</Link>)}</nav></aside>}
export function DashboardTop({role}:{role:string}){return <header className="dash-head" style={{height:72,borderBottom:'1px solid var(--line)',background:'#fff',padding:'0 30px',margin:'-30px -30px 30px'}}><div className="mobile-show"><Link href="/" className="logo"><span className="pin"/>CateFind</Link></div><div className="hidden md:flex field" style={{width:280,padding:8}}><Search size={16}/><input placeholder="Ara..."/></div><div style={{display:'flex',alignItems:'center',gap:12}}><button className="btn btn-light" aria-label="Bildirimler"><Bell size={17}/></button><span className="avatar" style={{width:38,height:38,borderRadius:'50%',fontSize:15}}>{role[0]}</span></div></header>}
export function DashboardShell({role,active,children}:{role:string;active:string;children:React.ReactNode}){return <div className="dashboard"><DashboardSidebar role={role} active={active}/><div className="dash-main"><DashboardTop role={role}/>{children}</div></div>}
export function StatsRow({items}:{items:{label:string;value:string}[]}){return <div className="stats">{items.map(x=><div className="card stat" key={x.label}><div className="label">{x.label}</div><div className="value">{x.value}</div><span className="badge">↗ Güncel</span></div>)}</div>}
export function MiniTable({rows}:{rows:{title:string;meta:string;status:string}[]}){return <div className="card card-pad"><table className="table"><tbody>{rows.map(r=><tr key={r.title}><td><b>{r.title}</b><div className="muted">{r.meta}</div></td><td><span className="badge">{r.status}</span></td><td><MoreHorizontal size={17}/></td></tr>)}</tbody></table></div>}
export function ProgressBar({label,value}:{label:string;value:number}){return <div><div style={{display:'flex',justifyContent:'space-between',fontSize:13,marginBottom:8}}><span>{label}</span><b>{value}%</b></div><div className="progress"><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
export function Rating({value=4.8}:{value?:number}){return <span className="rating">★ {value}</span>}
