'use client';

import Link from 'next/link';
import { SearchField, Stat } from '@santi020k/lumen-react';
import { ArrowRight, BadgeCheck, BarChart3, Bell, CalendarDays, CheckCircle2, ChevronRight, Clock3, Heart, LayoutDashboard, MessageCircle, MoreHorizontal, PackageCheck, Plus, Search, Settings, ShieldCheck, Star, Store, Users, UtensilsCrossed } from 'lucide-react';

export const firms = [
  { name: 'Lezzet Durağı Catering', slug: 'lezzet-duragi-catering', city: 'İstanbul', rating: 4.8, reviews: 120, response: 18, price: 42500, tags: ['Düğün & Davet', 'Kurumsal'], image: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=1200&q=85' },
  { name: 'Evin Yemekleri', slug: 'evin-yemekleri', city: 'İstanbul', rating: 4.6, reviews: 98, response: 24, price: 38500, tags: ['Ev Yemekleri', 'Kurumsal'], image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&q=85' },
  { name: 'Şefin Sofrası', slug: 'sefin-sofrasi', city: 'İstanbul', rating: 4.9, reviews: 210, response: 20, price: 62000, tags: ['VIP Catering', 'Özel Etkinlik'], image: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=1200&q=85' },
  { name: 'Anadolu Catering', slug: 'anadolu-catering', city: 'İstanbul', rating: 4.8, reviews: 190, response: 16, price: 36000, tags: ['Toplu Yemek', 'Kurumsal'], image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=85' },
  { name: 'Marin Food', slug: 'marin-food', city: 'İstanbul', rating: 4.8, reviews: 76, response: 28, price: 51000, tags: ['Kokteyl', 'Düğün & Davet'], image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&q=85' },
  { name: 'Gurme Tabak', slug: 'gurme-tabak', city: 'İstanbul', rating: 4.7, reviews: 84, response: 22, price: 45000, tags: ['Özel Etkinlik', 'VIP Catering'], image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=85' },
];

export function BrandMark() { return <span className="inline-grid h-10 w-10 place-items-center rounded-xl bg-cf-primary text-white shadow-sm"><UtensilsCrossed size={19}/></span>; }

export function PageHeader({ title, description, eyebrow='CateFind' }: { title: string; description?: string; eyebrow?: string }) {
  return <div className="mb-8"><div className="eyebrow">{eyebrow}</div><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1>{description && <p className="muted mt-3 max-w-2xl leading-7">{description}</p>}</div>;
}

export function FirmCard({ firm, compact=false }: { firm: typeof firms[number]; compact?: boolean }) {
  return <article className="card group overflow-hidden bg-white transition hover:-translate-y-0.5 hover:shadow-lg"><div className={`relative overflow-hidden ${compact ? 'h-36' : 'h-48'}`}><img src={firm.image} alt={firm.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-3 top-3 rounded-full bg-white/95 px-2.5 py-1 text-[11px] font-bold text-cf-primary">Doğrulanmış</span><button aria-label="Favorilere ekle" className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-white/95"><Heart size={17}/></button></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><Link href={`/firma/${firm.slug}`} className="flex items-center gap-2 font-bold text-lg hover:text-cf-primary">{firm.name}<BadgeCheck size={17} className="shrink-0 text-cf-primary"/></Link><div className="mt-1 flex items-center gap-1 text-sm"><Star size={14} fill="currentColor" className="text-amber-500"/> {firm.rating} <span className="muted">({firm.reviews} yorum)</span></div></div></div><div className="my-4 flex flex-wrap gap-2">{firm.tags.map(tag=><span key={tag} className="rounded-full bg-cf-accent px-2.5 py-1 text-xs font-medium text-cf-dark">{tag}</span>)}</div><div className="space-y-2 text-sm muted"><div className="flex items-center gap-2"><Store size={15}/>{firm.city}</div><div className="flex items-center gap-2"><Clock3 size={15}/>Ortalama {firm.response} dk içinde cevap</div></div><div className="mt-5 flex items-center justify-between border-t border-cf-border pt-4"><span className="font-bold">₺{firm.price.toLocaleString('tr-TR')}+ <small className="muted font-normal">başlayan</small></span><Link href={`/firma/${firm.slug}`} className="text-sm font-bold text-cf-primary">İncele <ArrowRight size={14} className="inline"/></Link></div></div></article>;
}

export function MarketplaceFilters() {
  return <aside className="card h-fit bg-white p-5 lg:sticky lg:top-24"><div className="flex items-center justify-between"><b>Filtreler</b><button className="text-xs font-bold text-cf-primary">Temizle</button></div><div className="mt-5 space-y-5"><label className="block text-sm font-semibold">Konum<select className="mt-2 h-11 w-full rounded-lg border border-cf-border bg-white px-3"><option>İstanbul</option><option>Ankara</option><option>İzmir</option></select></label><label className="block text-sm font-semibold">Hizmet Türü<select className="mt-2 h-11 w-full rounded-lg border border-cf-border bg-white px-3"><option>Tümü</option><option>Kurumsal Yemek</option><option>Düğün & Davet</option><option>Özel Etkinlikler</option></select></label><label className="block text-sm font-semibold">Fiyat Aralığı<input type="range" className="mt-3 w-full"/><div className="mt-1 flex justify-between text-xs muted"><span>₺0</span><span>₺250.000+</span></div></label><fieldset><legend className="text-sm font-semibold">Puan</legend><div className="mt-3 space-y-2 text-sm">{['5 yıldız','4 yıldız ve üzeri','3 yıldız ve üzeri'].map(x=><label key={x} className="flex gap-2"><input type="checkbox"/> {x}</label>)}</div></fieldset><fieldset><legend className="text-sm font-semibold">Özellikler</legend><div className="mt-3 space-y-2 text-sm">{['Helal Sertifikası','Vegan Menü','Profesyonel Ekip','Zamanında Teslimat'].map(x=><label key={x} className="flex gap-2"><input type="checkbox"/> {x}</label>)}</div></fieldset></div><button className="btn btn-primary mt-6 w-full">Sonuçları Göster</button></aside>;
}

export function DashboardSidebar({ role='Müşteri', active='Ana Sayfa' }: { role?: string; active?: string }) {
  const items = role === 'Firma' ? ['Ana Sayfa','Talepler','Teklifler','İlanlar','Menüler','Mesajlar','Yorumlar','Analitik','Profil','Ayarlar'] : role === 'Admin' ? ['Dashboard','Firmalar','Kullanıcılar','Talepler','Teklifler','İlanlar','Yorumlar','Kategoriler','Raporlar','Ayarlar'] : ['Ana Sayfa','Taleplerim','Tekliflerim','Mesajlarım','Favorilerim','Profil','Ayarlar'];
  return <aside className="hidden min-h-screen w-64 shrink-0 bg-cf-dark p-5 text-white lg:block"><div className="mb-8 flex items-center gap-2 text-xl font-bold"><BrandMark/><span>CateFind</span></div><div className="mb-3 text-[11px] font-bold uppercase tracking-[.15em] text-white/45">{role} Paneli</div><nav className="space-y-1">{items.map((item,i)=><Link key={item} href="#" className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${item===active ? 'bg-cf-primary text-white' : 'text-white/65 hover:bg-white/5 hover:text-white'}`}><span className="w-5 text-center">{i===0?<LayoutDashboard size={17}/>:i===1?<CalendarDays size={17}/>:i===2?<PackageCheck size={17}/>:i===3?<Store size={17}/>:i===4?<UtensilsCrossed size={17}/>:i===5?<MessageCircle size={17}/>:i===6?<Star size={17}/>:i===7?<BarChart3 size={17}/>:i===8?<Users size={17}/>:<Settings size={17}/>}</span>{item}</Link>)}</nav><div className="mt-8 border-t border-white/10 pt-5 text-xs text-white/45">© 2026 CateFind</div></aside>;
}

export function DashboardTop({ role }: { role: string }) { return <header className="flex h-16 items-center justify-between border-b border-cf-border bg-white px-5 sm:px-8"><div className="lg:hidden flex items-center gap-2 font-bold"><BrandMark/>CateFind</div><div className="hidden md:block"><SearchField placeholder="Ara..." className="w-72"/></div><div className="flex items-center gap-3"><button className="relative grid h-10 w-10 place-items-center rounded-full border border-cf-border"><Bell size={17}/><span className="absolute right-2 top-2 h-1.5 w-1.5 rounded-full bg-cf-primary"/></button><div className="flex items-center gap-2"><span className="grid h-9 w-9 place-items-center rounded-full bg-cf-accent text-sm font-bold text-cf-primary">{role[0]}</span><span className="hidden text-sm font-semibold sm:block">{role} Hesabı</span></div></div></header>; }

export function DashboardShell({ role, active, children }: { role: string; active: string; children: React.ReactNode }) { return <div className="min-h-screen bg-cf-bg lg:flex"><DashboardSidebar role={role} active={active}/><div className="min-w-0 flex-1"><DashboardTop role={role}/><main className="mx-auto max-w-[1400px] p-5 sm:p-8">{children}</main></div></div>; }

export function StatsRow({ items }: { items: { label: string; value: string }[] }) { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{items.map((s,i)=><Stat key={s.label} label={s.label} value={s.value} variant={i===0?'accent':'default'}/>)}</div>; }

export function MiniTable({ rows }: { rows: { title: string; meta: string; status: string }[] }) { return <div className="overflow-hidden rounded-2xl border border-cf-border bg-white"><div className="grid grid-cols-[1fr_auto_auto] gap-4 border-b border-cf-border px-5 py-3 text-xs font-bold uppercase tracking-wider muted"><span>Talep</span><span>Durum</span><span></span></div>{rows.map(r=><div key={r.title} className="grid grid-cols-[1fr_auto_auto] items-center gap-4 border-b border-cf-border px-5 py-4 last:border-0"><div><div className="font-bold">{r.title}</div><div className="mt-1 text-xs muted">{r.meta}</div></div><span className="rounded-full bg-cf-accent px-2.5 py-1 text-xs font-bold text-cf-primary">{r.status}</span><MoreHorizontal size={18} className="muted"/></div>)}</div>; }

export function ProgressBar({ label, value }: { label: string; value: number }) { return <div><div className="mb-2 flex justify-between text-sm"><span>{label}</span><b>{value}%</b></div><div className="h-2 rounded-full bg-cf-accent"><div className="h-2 rounded-full bg-cf-primary" style={{width:`${value}%`}}/></div></div>; }

export function Rating({ value=4.8 }: { value?: number }) { return <span className="inline-flex items-center gap-1 text-sm font-bold"><Star size={14} fill="currentColor" className="text-amber-500"/>{value}</span>; }
