import Link from 'next/link';
import { BadgeCheck, Clock3, Heart, MapPin, MessageCircle, ShieldCheck, Star, Users, UtensilsCrossed } from 'lucide-react';
import { Header } from '@/components/header';
import { FirmCard, Rating } from '@/components/lumen-marketplace';

export default async function CompanyPage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params;
  const firm = { name: slug.split('-').map(x=>x[0]?.toUpperCase()+x.slice(1)).join(' '), city:'İstanbul', rating:4.8, reviews:120, response:18, price:42500, tags:['Düğün & Davet','Kurumsal'], image:'https://images.unsplash.com/photo-1555244162-803834f70033?w=1600&q=85' };
  return <><Header/><main>
    <section className="relative h-64 overflow-hidden sm:h-80"><img src={firm.image} alt="Catering etkinliği" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-black/35"/></section>
    <div className="container relative -mt-16"><section className="card bg-white p-6 shadow-xl sm:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-center"><div className="grid h-24 w-24 shrink-0 place-items-center rounded-2xl border-4 border-white bg-cf-accent text-2xl font-bold text-cf-dark shadow"><UtensilsCrossed size={32}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold sm:text-3xl">{firm.name}</h1><BadgeCheck className="text-cf-primary"/><span className="rounded-full bg-cf-accent px-2.5 py-1 text-xs font-bold text-cf-primary">Doğrulanmış Firma</span></div><div className="mt-3 flex flex-wrap gap-4 text-sm muted"><span><Rating value={firm.rating}/> <span className="ml-1">({firm.reviews} yorum)</span></span><span className="flex items-center gap-1"><MapPin size={15}/>{firm.city}</span><span className="flex items-center gap-1"><Clock3 size={15}/>~{firm.response} dk cevap</span><span className="flex items-center gap-1"><Users size={15}/>800 kişiye kadar</span></div></div><div className="flex gap-2"><button className="btn btn-secondary" aria-label="Favorilere ekle"><Heart size={18}/></button><Link href={`/firma/${slug}/teklif`} className="btn btn-primary">Teklif Al</Link></div></div></section>
      <div className="grid gap-8 py-8 lg:grid-cols-[1fr_320px]"><div><nav className="mb-8 flex gap-1 overflow-x-auto border-b border-cf-border pb-2">{['Genel Bakış','Hizmetler','Menüler','Yorumlar','Fotoğraflar','İletişim'].map((x,i)=><a key={x} href={`#${i===0?'genel':x.toLowerCase()}`} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-bold ${i===0?'bg-cf-accent text-cf-primary':'muted hover:bg-white'}`}>{x}</a>)}</nav><section id="genel"><h2 className="text-2xl font-bold">Hakkımızda</h2><p className="muted mt-3 max-w-3xl leading-7">Profesyonel catering hizmetleri, deneyimli servis ekibi ve etkinliğinize özel menü çözümleri. CateFind üzerinden ihtiyaçlarınızı paylaşarak bu firma ile doğrudan teklif sürecine başlayabilirsiniz.</p><div className="mt-6 grid gap-3 sm:grid-cols-4">{[['Helal Sertifikası',ShieldCheck],['Profesyonel Ekip',Users],['Zamanında Teslimat',Clock3],['Özel Menü Tasarımı',UtensilsCrossed]].map(([t,I])=>{const Icon=I as typeof ShieldCheck; return <div key={String(t)} className="card bg-white p-4"><Icon size={19} className="text-cf-primary"/><b className="mt-3 block text-sm">{String(t)}</b></div>})}</div></section><section id="menüler" className="mt-10"><h2 className="text-2xl font-bold">Örnek Menüler</h2><div className="mt-4 grid gap-4 sm:grid-cols-3">{['Standart Menü','Premium Menü','VIP Menü'].map((m,i)=><div className="card overflow-hidden bg-white" key={m}><img src={['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80','https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&q=80','https://images.unsplash.com/photo-1555244162-803834f70033?w=800&q=80'][i]} alt={m} className="h-40 w-full object-cover"/><div className="p-4"><b>{m}</b><p className="muted mt-1 text-sm">Başlangıç · Ana yemek · Tatlı · İçecek</p></div></div>)}</div></section><section id="yorumlar" className="mt-10"><h2 className="text-2xl font-bold">Müşteri Yorumları</h2><div className="card mt-4 bg-white p-5"><Rating value={4.8}/><p className="mt-3 font-bold">“Etkinliğimiz baştan sona çok iyi yönetildi.”</p><p className="muted mt-1 text-sm">Doğrulanmış müşteri · 2 hafta önce</p></div></section></div><aside className="card h-fit bg-white p-6 lg:sticky lg:top-24"><div className="text-sm muted">500 kişilik paketlerden</div><div className="mt-1 text-2xl font-bold">₺{firm.price.toLocaleString('tr-TR')}+</div><p className="muted mt-1 text-sm">Paket ve kişi sayısına göre değişir.</p><Link href={`/firma/${slug}/teklif`} className="btn btn-primary mt-5 w-full">Teklif Talep Et</Link><Link href="/firma-ariyorum" className="btn btn-secondary mt-2 w-full">Firma Arıyorum</Link><div className="mt-5 flex gap-2 border-t border-cf-border pt-5 text-sm muted"><MessageCircle size={17}/> Ortalama {firm.response} dakikada yanıt</div></aside></div>
    </div>
  </main></>;
}
