'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Save } from 'lucide-react';

export default function NewListingPage() {
  const [saved, setSaved] = useState(false);
  return <main className="min-h-screen"><div className="container max-w-3xl py-10"><Link href="/firma/panel" className="inline-flex items-center gap-2 text-sm font-bold text-cf-primary"><ArrowLeft size={16}/>Panele dön</Link><div className="mt-7"><div className="eyebrow">Firma Paneli</div><h1 className="text-4xl font-bold mt-2">Yeni ilan oluştur</h1><p className="muted mt-3">Hizmetini müşterilerin kolayca anlayacağı şekilde tanımla.</p></div><form className="card p-6 sm:p-8 mt-8 grid gap-5" onSubmit={(e)=>{e.preventDefault();setSaved(true)}}><label className="grid gap-2 text-sm font-bold">İlan başlığı<input required className="h-12 border border-cf-border rounded-xl px-3 font-normal" placeholder="Örn. 500 kişilik düğün menüsü"/></label><label className="grid gap-2 text-sm font-bold">Kategori<select className="h-12 border border-cf-border rounded-xl px-3 font-normal"><option>Düğün & Davet</option><option>Kurumsal Yemek</option><option>Toplantı & Seminer</option><option>VIP Catering</option></select></label><label className="grid gap-2 text-sm font-bold">Açıklama<textarea required className="min-h-32 border border-cf-border rounded-xl p-3 font-normal" placeholder="Menü, servis, teslimat ve paket detaylarını anlat…"/></label><div className="grid sm:grid-cols-2 gap-4"><label className="grid gap-2 text-sm font-bold">Başlangıç fiyatı<input required type="number" min="0" className="h-12 border border-cf-border rounded-xl px-3 font-normal" placeholder="42500"/></label><label className="grid gap-2 text-sm font-bold">Minimum kişi<input required type="number" min="1" className="h-12 border border-cf-border rounded-xl px-3 font-normal" placeholder="100"/></label></div><button className="btn btn-primary justify-center"><Save size={17}/>{saved?'Taslak kaydedildi':'İlanı kaydet'}</button></form></div></main>;
}
