import Link from 'next/link';
import { Heart, MapPin, Search, Sparkles, Star } from 'lucide-react';
import { Header } from '@/components/header';

const firms = [
  {name:'Lezzet Durağı Catering',slug:'lezzet-duragi-catering',city:'İstanbul',rating:4.8,reviews:120,response:18,price:'₺42.500+',tags:['Düğün & Davet','Kurumsal'],image:'https://images.unsplash.com/photo-1555244162-803834f70033?w=1200&q=85'},
  {name:'Evin Yemekleri',slug:'evin-yemekleri',city:'İstanbul',rating:4.6,reviews:98,response:24,price:'₺38.500+',tags:['Ev Yemekleri','Kurumsal'],image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&q=85'},
  {name:'Şefin Sofrası',slug:'sefin-sofrasi',city:'İstanbul',rating:4.9,reviews:210,response:20,price:'₺62.000+',tags:['VIP Catering','Özel Etkinlik'],image:'https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=1200&q=85'},
  {name:'Anadolu Catering',slug:'anadolu-catering',city:'İstanbul',rating:4.8,reviews:190,response:16,price:'₺36.000+',tags:['Toplu Yemek','Kurumsal'],image:'https://images.unsplash.com/photo-1547592180-85f173990554?w=1200&q=85'},
  {name:'Marin Food',slug:'marin-food',city:'İstanbul',rating:4.8,reviews:76,response:28,price:'₺51.000+',tags:['Kokteyl','Düğün & Davet'],image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=1200&q=85'},
  {name:'Gurme Tabak',slug:'gurme-tabak',city:'İstanbul',rating:4.7,reviews:84,response:22,price:'₺45.000+',tags:['Özel Etkinlik','VIP Catering'],image:'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1200&q=85'},
];

export default function Firms(){return <><Header/><main className="container">
  <section className="page-title"><div className="eyebrow">Marketplace</div><h1>Catering Firmaları</h1><p className="muted">Şehrine, hizmetine ve etkinlik türüne göre catering firmalarını keşfet.</p></section>
  <div className="market-layout"><aside className="card filters"><h3>Filtrele</h3><div className="filter"><h4>Şehir</h4><select className="field" style={{width:'100%'}} defaultValue="İstanbul"><option>İstanbul</option><option>Ankara</option><option>İzmir</option></select></div><div className="filter"><h4>Hizmet kategorisi</h4>{['Kurumsal Yemek','Düğün & Davet','Okul Yemekleri','Özel Etkinlikler'].map(x=><label className="check" key={x}><input type="checkbox"/> {x}</label>)}</div><div className="filter"><h4>Puan</h4>{['5 yıldız','4 yıldız ve üzeri','3 yıldız ve üzeri'].map(x=><label className="check" key={x}><input type="radio" name="rating"/> {x}</label>)}</div><div className="filter"><h4>Özellik</h4>{['Helal Sertifikası','Vegan','Hızlı Teslimat'].map(x=><label className="check" key={x}><input type="checkbox"/> {x}</label>)}</div><Link href="/catering-firmalari" className="btn btn-green" style={{width:'100%',marginTop:16}}>Sonuçları göster</Link></aside>
  <section><div className="card searchbar"><Search size={18} style={{marginTop:8}}/><input placeholder="Firma, hizmet veya kategori ara"/><select defaultValue="recommended"><option value="recommended">Önerilen</option><option>En yüksek puan</option><option>En hızlı cevap</option><option>En yeni</option></select></div><div className="results-top"><span>{firms.length * 10 + 68} firma bulundu</span><span className="flex items-center gap-1"><Sparkles size={15}/> Önerilen sıralama</span></div><div className="listing-grid">{firms.map(f=><article className="card company-card" key={f.slug}><div className="company-photo"><img src={f.image} alt={f.name}/><button className="heart" aria-label={`${f.name} favorilere ekle`}><Heart size={18}/></button></div><div className="company-body"><div className="company-title"><h3>{f.name} ✓</h3><span className="rating"><Star size={13} fill="currentColor"/> {f.rating}</span></div><div className="muted">{f.city} · {f.reviews} yorum</div><div className="chips">{f.tags.map(t=><span className="chip" key={t}>{t}</span>)}</div><div className="meta"><span><MapPin size={13} style={{display:'inline'}}/> {f.city}</span><span>◷ Ortalama {f.response} dk cevap</span></div><div className="company-foot"><span>{f.price}</span><Link href={`/firma/${f.slug}`} style={{color:'var(--green)'}}>Profili Gör →</Link></div></div></article>)}</div></section>
  </div>
</main><Footer/></>}

function Footer(){return <footer className="footer"><div className="container footer-grid"><div><div className="logo"><span className="pin"/>CateFind</div><p className="muted">Catering firmaları ve müşteriler için güvenilir marketplace.</p></div><div><b>Keşfet</b><Link href="/catering-firmalari">Catering Firmaları</Link><Link href="/hizmetler">Hizmetler</Link><Link href="/firma-ariyorum">Firma Arıyorum</Link></div><div><b>Platform</b><Link href="/nasil-calisir">Nasıl Çalışır?</Link><Link href="/blog">Blog</Link><Link href="/iletisim">İletişim</Link></div><div><b>Yasal</b><Link href="#">KVKK</Link><Link href="#">Gizlilik</Link><Link href="#">Çerez Politikası</Link></div></div></footer>}
